"use strict";

const ROLES = Object.freeze({
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  SALES: "SALES",
  SUPPORT: "SUPPORT",
  CUSTOMER: "CUSTOMER",
});

const BOOKINGS = Object.freeze({
  PENDING_PAYMENT: "PENDING_PAYMENT",
  PAYMENT_PROCESSING: "PAYMENT_PROCESSING",
  CONFIRMED: "CONFIRMED",
  CANCELLED: "CANCELLED",
  REFUND_REQUESTED: "REFUND_REQUESTED",
  REFUND_PROCESSING: "REFUND_PROCESSING",
  REFUNDED: "REFUNDED",
  FAILED: "FAILED",
});

const BOOKING_TYPE = Object.freeze({
  FLIGHT: "FLIGHT",
  HOTEL: "HOTEL",
  CAR: "CAR",
});

const PAYMENT_STATUS = Object.freeze({
  PENDING: "PENDING",
  PROCESSING: "PROCESSING",
  COMPLETED: "COMPLETED",
  REFUNDED: "REFUNDED",
  FAILED: "FAILED",
  PARTIALLY_REFUNDED: "PARTIALLY_REFUNDED",
  REFUND_PROCESSING: "REFUND_PROCESSING",
});

const PAYMENT_PROVIDER = Object.freeze({
  STRIPE: "stripe",
  DUFFEL: "duffel",
});

const TICKET_STATUS = Object.freeze({
  OPEN: "OPEN",
  CLOSED: "CLOSED",
  IN_PROGRESS: "IN_PROGRESS",
  RESOLVED: "RESOLVED",
});

const NOTIFICATION_TYPES = Object.freeze({
  BOOKING_CONFIRMED: "BOOKING_CONFIRMED",
  BOOKING_CANCELLED: "BOOKING_CANCELLED",
  PAYMENT_PROCESSED: "PAYMENT_PROCESSED",
  PAYMENT_RECEIVED: "PAYMENT_RECEIVED",
  REFUND_PROCESSED: "REFUND_PROCESSED",
  SUPPORT_TICKET_UPDATED: "SUPPORT_TICKET_UPDATED",
});

const ACTIVITY_LOGS = Object.freeze({
  USER_REGISTERED: "USER_REGISTERED",
  USER_LOGGED_IN: "USER_LOGGED_IN",
  BOOKING_CREATED: "BOOKING_CREATED",
  BOOKING_CONFIRMED: "BOOKING_CONFIRMED",
  BOOKING_CANCELLED: "BOOKING_CANCELLED",
  PAYMENT_INITIALIZED: "PAYMENT_INITIALIZED",
  PAYMENT_COMPLETED: "PAYMENT_COMPLETED",
  REFUND_REQUESTED: "REFUND_REQUESTED",
  REFUND_PROCESSED: "REFUND_PROCESSED",
  ADMIN_ACTION: "ADMIN_ACTION",
});

const HTTP = Object.freeze({
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE: 422,
  TOO_MANY_REQUEST: 429,
  INTERNAL_ERROR: 500,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
});

const PAGINATION = Object.freeze({
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 10,
  MAX_LIMIT: 100,
});

const CABIN_CLASS = Object.freeze({
  ECONOMY: "economy",
  PREMIUM_ECONOMY: "premium_economy",
  BUSINESS: "business",
  FIRST: "first",
});

const TRIP_TYPE = Object.freeze({
  ONE_WAY: "ONE_WAY",
  ROUND_TRIP: "ROUND_TRIP",
  MULTI_CITY: "MULTI_CITY",
});

module.exports = {
  ROLES,
  BOOKINGS,
  BOOKING_TYPE,
  PAYMENT_STATUS,
  PAYMENT_PROVIDER,
  TICKET_STATUS,
  NOTIFICATION_TYPES,
  ACTIVITY_LOGS,
  HTTP,
  PAGINATION,
  CABIN_CLASS,
  TRIP_TYPE,
};
